import javax.swing.*;
import java.awt.*;
import java.net.MalformedURLException;
import java.net.URL;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nadcr
 */
public class Driver extends javax.swing.JFrame {

    /**
     * Creates new form Driver
     */
    private Client client;
    private String orgName = "";
    private String reqLoc = "";

    public Driver(Client client) {
        this.client = client;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        //AIzaSyCULZ5IzPsVtZQXGTPoiE--RTy2JFQRjyo
        //https://maps.googleapis.com/maps/api/staticmap?center=800,David,Ross,Road&zoom=13&size=400x400&
        //markers=color:blue%7Clabel:S%800,David,Ross,Rd&key=AIzaSyCULZ5IzPsVtZQXGTPoiE--RTy2JFQRjyo
        logonName = new javax.swing.JTextField();
        logonButton = new javax.swing.JButton("Log on");
        jDialog1 = new javax.swing.JDialog();
        aboutdialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        freebtn = new javax.swing.JRadioButton();
        customerbtn = new javax.swing.JRadioButton();
        offbtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitmenu = new javax.swing.JMenuItem();
        aboutmenu = new javax.swing.JMenu();
        try {
            URL img = new URL(client.getMapImage());
            ImageIcon image = new ImageIcon(img);
            googleMapThing = new javax.swing.JLabel(image);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }




        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout aboutdialogLayout = new javax.swing.GroupLayout(aboutdialog.getContentPane());
        aboutdialog.getContentPane().setLayout(aboutdialogLayout);
        aboutdialogLayout.setHorizontalGroup(
                aboutdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        aboutdialogLayout.setVerticalGroup(
                aboutdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("What is your driver status:");
        jLabel1.setToolTipText("");

        freebtn.setText("Free for pickup");

        customerbtn.setText("With customer");

        offbtn.setText("Off the clock");

        jLabel2.setText("Passenger Address is:");

        jLabel3.setText("Passenger  name is:");

        jLabel4.setText("Directions to address:");

        jMenu1.setText("File");

        exitmenu.setText("Exit");
        exitmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitmenu);

        jMenuBar1.add(jMenu1);

        aboutmenu.setText("About");
        aboutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutmenuActionPerformed(evt);
            }
        });

        logonButton.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                logonButtonActionPerformed(evt);
            }
        });
        jMenuBar1.add(aboutmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(logonName,javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(logonButton)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        //.addComponent(freebtn)
                                                        //.addComponent(customerbtn)
                                                        //.addComponent(offbtn)
                                                        )
                                                .addGap(148, 148, 148)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabel3)
                                                .addComponent( googleMapThing )
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(logonButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        //.addComponent(freebtn)
                                        .addComponent(jLabel2)
                                        .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                 //               .addComponent(customerbtn))
                                )
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel4)))
                                                .addComponent(googleMapThing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                //.addComponent(offbtn)
                                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitmenuActionPerformed

    private void aboutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutmenuActionPerformed
        JOptionPane.showMessageDialog(aboutdialog, "For questions email support@soberuber.com");
    }//GEN-LAST:event_aboutmenuActionPerformed

    private void logonButtonActionPerformed(java.awt.event.ActionEvent evt){

      String[] returnInfo = client.logonDriver(logonName.getText()).split("-");
      if(returnInfo[0].equals("DRIVER NOT FOUND")){
          logonName.setText(returnInfo[0]);
      }else {
          orgName = returnInfo[0];
          reqLoc = returnInfo[1];
          addresstxt.setText(reqLoc);
          nametxt.setText(returnInfo[2]);
          if(!returnInfo[1].equals("NO RIDE REQUESTED")) {
              try {
                  URL img = new URL(formatLocation());
                  ImageIcon image = new ImageIcon(img);
                  googleMapThing.setIcon(image);
              } catch (MalformedURLException m) {
                  m.printStackTrace();
              }
          }
      }
    }

    public String formatLocation(){
        String rideToGiveLocation = "";
        String homeAddress = "";
        String urlFormatPt1 = "https://maps.googleapis.com/maps/api/staticmap?center=";
        String frmtPt2 = "&zoom=13&size=400x400&markers=color:red%7C";
        String keyFrmt = "&key=AIzaSyCULZ5IzPsVtZQXGTPoiE--RTy2JFQRjyo";
        if(orgName.equals("THETA_CHI")){
            homeAddress = "800+David+Ross+Rd";
        }else if(orgName.equals("PHI_DELTA_THETA")){
            homeAddress = "503+W+State+St+West+lafayette";
        }else if(orgName.equals("TAU_BETA_SIGMA")){
            homeAddress = "329+W+State+St+west+lafayette";
        }else{
            homeAddress = "501+Buckland+Rd+Matamata";
        }
        if(!reqLoc.equals("")) {
            String[] addressParts = reqLoc.split(" ");
            String rebuiltRider = "";
            for(int i = 0;i<addressParts.length;i++){
                if(i+1 == addressParts.length) {
                    rebuiltRider += addressParts[i];
                }else{
                    rebuiltRider += addressParts[i] + "+";
                }
            }
            System.out.println(rebuiltRider);

            rideToGiveLocation = urlFormatPt1+homeAddress+frmtPt2+rebuiltRider+keyFrmt;

        }else{
            homeAddress = "501+Buckland+Rd+Matamata";
            rideToGiveLocation = urlFormatPt1+homeAddress+frmtPt2+homeAddress+keyFrmt;

        }

        return rideToGiveLocation;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog aboutdialog;
    private javax.swing.JMenu aboutmenu;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JRadioButton customerbtn;
    private javax.swing.JMenuItem exitmenu;
    private javax.swing.JRadioButton freebtn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JRadioButton offbtn;
    private javax.swing.JButton logonButton;
    private javax.swing.JTextField logonName;
    private javax.swing.JLabel googleMapThing;
    // End of variables declaration//GEN-END:variables
}